# How to generate to valid deploy_rsa.enc file ?
#
# Generate a dedicated SSH key :
# ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f ./deploy_rsa
# 
# Encrypt the private key and add $encrypted_xxx_key and $encrypted_xxx_key to the env
# travis login --org
# sous windows (gitbash):
# - travis encrypt key_password=exemplepassword
# - gpg -c deploy_rsa
# - Then add secure env variable and "echo $key_password | gpg --passphrase-fd 0 deploy_rsa.gpg" to the defore-reploy
# sous Linux : 
# - travis encrypt-file deploy_rsa -p --add
#   (auto add the line openssl aes-256-cbc -K $encrypted_d68160cf0aa5_key -iv $encrypted_d68160cf0aa5_iv -in deploy_rsa.enc -out deploy_rsa -d)
# 
# Copy the public key onto the remote SSH server
# ssh-copy-id -i deploy_rsa.pub loireatl-ds@ssh.cluster011.hosting.ovh.net
# ssh-copy-id -i deploy_rsa.pub loireatl-devds@ssh.cluster011.hosting.ovh.net
# 
# Remove the key from your computer
# rm -f deploy_rsa deploy_rsa.pub
# 
# Add the key to github
# git add deploy_rsa.enc
# 
env:
  global:
    secure: "EZ1p4bNLpqVeg5LP+fikJJI+61nM773d8pUenC9yqTdrY6ubeZbuKGlR4EMMMnRAW+8IobBlE3FjcIt4ulJPJFjBt1GV8qrI83q/1j02G3S3nEhi5XFdXiR9w5LiSkG0FxBiyRpzRGT7gR8Fg+2jq7IOaaU9h98O35URato1F9GtqJ9uKiSc0jbfrT8T5Mom6502F+vvbIait2kyLQ5ZH7kWz6i7QPs8lVQ0Zirf5n4AkUWxemXL6ff+txV+Nu55jhTTn9cExOj50AmAMwqCF7Yp/XoU7IDGTiZvTVM0qBnWFaVd6teotGUflXxY6SbS6wmyR0EaN6mQ2ZIaamZ00e0IcMKgnQNxs5NWdlLZicu7E6wJ1kUmxBmOjMIzL+HHKr8KJth52wqo6wNQe2KwwoGLuu0jvChHFVyJLvv8eswPsq4d/nwiVNQ0njwJW7oKTYFbGiZBJRHNLKAFOt0aBytPEItCWNAEbh4IsXGRBuSPfkJ3rLMZF88hGREzHu4rzD5ka0PeBcFO75sLXZ+kFgtbu+48TulcdwgVKlGlul4oo7Joug0//Iaop9/hiPz9ZR6hFa2vlaFZXbLb2QfMI3FLg/OX+WnoMiNIzlAhyqiL9S2Az6JKQTziozIRSOTk2xLetnJpipgLCQvK4afj+K+eEONmyIuV3IOK1QGMsME="

addons:
  ssh_known_hosts: ssh.cluster011.hosting.ovh.net
  
install:
  - npm install -g gulp-cli
  - npm install

script: 
  - gulp build

# Unlock private key
before_deploy:
  - echo $key_password | gpg --passphrase-fd 0 deploy_rsa.gpg
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet --exclude .ssh $TRAVIS_BUILD_DIR/dist/ loireatl-ds@ssh.cluster011.hosting.ovh.net:/home/loireatl-ds/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet --exclude .ssh $TRAVIS_BUILD_DIR/dist/ loireatl-devds@ssh.cluster011.hosting.ovh.net:/home/loireatl-devds/
    on:
      branch: recette