# How to generate to valid deploy_rsa.enc file ?
#
# Generate a dedicated SSH key :
# ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f ./deploy_rsa
# 
# Encrypt the private key and add $encrypted_xxx_key and $encrypted_xxx_key to the env
# travis login --org
# sous windows (gitbash):
# - travis encrypt key_password=exemplepassword
# - gpg -c deploy_rsa
# - Then add secure env variable and "echo $key_password | gpg --passphrase-fd 0 deploy_rsa.gpg" to the defore-reploy
# sous Linux : 
# - travis encrypt-file deploy_rsa -p --add
#   (auto add the line openssl aes-256-cbc -K $encrypted_d68160cf0aa5_key -iv $encrypted_d68160cf0aa5_iv -in deploy_rsa.enc -out deploy_rsa -d)
# 
# Copy the public key onto the remote SSH server
# ssh-copy-id -i deploy_rsa.pub loireatl-ds@ssh.cluster011.hosting.ovh.net
# ssh-copy-id -i deploy_rsa.pub loireatl-devds@ssh.cluster011.hosting.ovh.net
# 
# Remove the key from your computer
# rm -f deploy_rsa deploy_rsa.pub
# 
# Add the key to github
# git add deploy_rsa.enc
# 
env:
  global:
    secure: "MP1b9TMwdtDmc9DLsnI6hzD31BMvMxNphUqDJPpcNHLAPEb2O7RJF2kWGW1GwaJpXLuGIgZc+vQa8WfIy7wnJYzWC8czdrLNffIOcGYA54v4co+ewMW0NxD8ux+OKBynglND/eYtE8rzx1TYa8JshF5yoHlGNVwnsH1MrvLI/HgTqaHNolL769aO7+xd+IRg7P5scIKpeOnmmLVQ4KMiFfMlBT+x+Ibr6TYhSzvAoJBNB+aLfNgi71mh2AyFQxfC6nQ4FKI49c4FOp4jxQXxTaUeIyqg4lCnzkmCVFKcjuaC78p4lhf3ylypz0Mz4U6qpAsiNMgAxmyeige+MGZBUPko7XKdBx5VdD+T27L5ic7CsoYnboSxi1HK0kY+DxL9+XmuFcubbrlnWA2Td6vE2CV8TahAWIXF0SEdoFFpw4escz5opZ5nbJIO/ghOdVOl1bzmV/R1GjwVcLRd5ZtM4ym7lm5oXiPBQNwYkdKDBuJdNlCme9kA2151JXaUqsVqd3V0iZ1QYDSoXPG6KW3NipQIKIo1YbjgjQwXJkCnKBCu9JGtqw4YZeYbAJvFQbBxEDzP9DAtZmBcPZF3v7uLI67KKPKOlm4oesmP2z4DANT62X6LBKje7zfJ4tykku4h2C4DccyajqDQZcQhCIl5NU6gQSz3rkcPzeHl1wZt0qI="

addons:
  ssh_known_hosts: ssh.cluster011.hosting.ovh.net
  
install:
  - npm install -g gulp-cli
  - npm install

script: 
  - gulp build

# Unlock private key
before_deploy:
  - echo $key_password | gpg --passphrase-fd 0 deploy_rsa.gpg
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet --exclude .ssh $TRAVIS_BUILD_DIR/dist/ loireatl-ds@ssh.cluster011.hosting.ovh.net:/home/loireatl-ds/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet --exclude .ssh $TRAVIS_BUILD_DIR/dist/ loireatl-devds@ssh.cluster011.hosting.ovh.net:/home/loireatl-devds/
    on:
      branch: recette